### PR TITLE
Add get active slot /slots/{slotId} to REST api, use utils/json

### PR DESCRIPTION
**Pull request by emizzle**
- Add endpoint /slots/{slotId} to get an active SalesAgent from the Sales module. Used in integration tests to test when a sale has reached a certain state. Those integration test changes will be included in a larger PR, coming later.
- Add OpenAPI changes for new endpoint and associated components
- Use utils/json instead of nim-json-serialization. Required exemption of imports from several packages that export nim-json-serialization by default.

This is a PR that is a smaller chunk of https://github.com/codex-storage/nim-codex/pull/607 to attempt to make it smaller and more digestible.

### CODE REVIEW

**Review by markspanbroek — APPROVED** [review]
Looks good to me.

**Comment by dryajov** [comment]
LGTM, but quick question - why are we excluding this exports "`%`, `%*`, toJson"? Is this because something else is leaking them?

**Comment by emizzle** [comment]
> why are we excluding this exports "%, %*, toJson"? Is this because something else is leaking them?

@dryajov yes, `utils/json` defines these (and exports them), so that it can be a drop-in replacement for `std/json`. `chronicles` exports `toJson` (from `nim-json-serialization`), so there is an ambiguous declaration that was attempted to be avoided. `ethers` and a few others also export `std/json` so have to avoid ambiguous declarations there too.

I've updated all the `import/export chronicles except` to only include `toJson` as `%` and `%*` were not being exported by chronicles.

**Comment by dryajov** [comment]
> > why are we excluding this exports "%, %*, toJson"? Is this because something else is leaking them?
> 
> @dryajov yes, `utils/json` defines these (and exports them), so that it can be a drop-in replacement for `std/json`. `chronicles` exports `toJson` (from `nim-json-serialization`), so there is an ambiguous declaration when modules import both `utils/json` and `pkg/chronicles` that was attempted to be avoided. `ethers` and a few others also export `std/json` so have to avoid ambiguous declarations with `%` and `%*` when importing them and `utils/json` too.
> 
> I've updated all the `import/export chronicles except` to only include `toJson` as `%` and `%*` were not being exported by chronicles.

Hmm, have we tried the json sink with this change, I have a suspicion that it might break it?

**Comment by emizzle** [comment]
> Hmm, have we tried the json sink with this change, I have a suspicion that it might break it?

Wouldn't that be a compile-time error? I've tried `build/codex --log-format=json` on this branch and it works (haven't let do much besides bootstrap)

```shell
❯ build/codex --log-format=json
{"lvl":"WRN","ts":"2023-12-06 16:05:47.727+11:00","msg":"`--nat` is set to loopback, your node wont properly announce over the DHT","topics":"codex","tid":9842787}
{"lvl":"INF","ts":"2023-12-06 16:05:47.727+11:00","msg":"Found a network private key","tid":9842787}
{"lvl":"INF","ts":"2023-12-06 16:05:47.731+11:00","msg":"Discovery SPR initialized","topics":"discv5","tid":9842787,"seqNum":1701839147,"uri":"spr:CiUIAhIhAlEVk3MM1HDQTFcwBFzrF4SsV9wx8VMuHVIoPUP0xP_BEgIDARo7CicAJQgCEiECURWTcwzUcNBMVzAEXOsXhKxX3DHxUy4dUig9Q_TE_8EQq4LAqwYaCgoIBAAAAAAGAAAqRjBEAiBYpgqmc6r0mlSp2GpXEv7esqmeC6mhPYLi7yE3PaO43AIgadScQbauNlx8fCc4kuWBm5erCThToyrb3nLHORiTplI"}
{"lvl":"NOT","ts":"2023-12-06 16:05:47.733+11:00","msg":"Current bytes used for cache quota","topics":"codex repostore","tid":9842787,"bytes":0}
{"lvl":"NOT","ts":"2023-12-06 16:05:47.733+11:00","msg":"Current bytes used for persist quota","topics":"codex repostore","tid":9842787,"bytes":0}
{"lvl":"INF","ts":"2023-12-06 16:05:47.734+11:00","msg":"Updated discovery SPR","topics":"discv5","tid":9842787,"uri":"spr:CiUIAhIhAlEVk3MM1HDQTFcwBFzrF4SsV9wx8VMuHVIoPUP0xP_BEgIDARo7CicAJQgCEiECURWTcwzUcNBMVzAEXOsXhKxX3DHxUy4dUig9Q_TE_8EQq4LAqwYaCgoIBH8AAAEG5-kqRzBFAiEA_K0H8jRwDdbVktUI9mSqdVEOz64JsY6dzvQpNgnISy8CIBXmSde6kvfscsoZxaGrHXEpY_wGiVkjmv7ssqOw2v6y"}
{"lvl":"INF","ts":"2023-12-06 16:05:47.734+11:00","msg":"Updated discovery SPR","topics":"discv5","tid":9842787,"uri":"spr:CiUIAhIhAlEVk3MM1HDQTFcwBFzrF4SsV9wx8VMuHVIoPUP0xP_BEgIDARo8CicAJQgCEiECURWTcwzUcNBMVzAEXOsXhKxX3DHxUy4dUig9Q_TE_8EQq4LAqwYaCwoJBH8AAAGRAh-aKkcwRQIhAIg3YCFN-IitLWNc-cfxq7TZq-ac89d0gENsrSWX8yc5AiAQDECsdG6OHqRPBdY0VDI4Yv5_GCQV7XyciDd2MccnPg"}
{"lvl":"INF","ts":"2023-12-06 16:05:47.734+11:00","msg":"Starting discovery node","topics":"discv5","tid":9842787,"node":"2e*0ae0a3:0.0.0.0:8090"}
{"lvl":"INF","ts":"2023-12-06 16:05:47.734+11:00","msg":"Starting transport","topics":"discv5","tid":9842787,"bindAddress":"0.0.0.0:8090"}
{"lvl":"NOT","ts":"2023-12-06 16:05:47.734+11:00","msg":"Started codex node","topics":"codex node","tid":9842787,"id":"16Uiu2HAkztC5ucHscZwBwXwHfPm4gruJpSYqwLhNPs4MrHxDFNqW","addrs":[{"data":{"buffer":[4,0,0,0,0,6,231,233],"offset":0}}]}
{"lvl":"NOT","ts":"2023-12-06 16:05:47.735+11:00","msg":"REST service started","tid":9842787,"address":"127.0.0.1:8080"}
```

**Comment by dryajov** [comment]
> > Hmm, have we tried the json sink with this change, I have a suspicion that it might break it?
> 
> Wouldn't that be a compile-time error? I've tried `build/codex --log-format=json` on this branch and it works (haven't let do much besides bootstrap)
> 
> ```shell
> ❯ build/codex --log-format=json
> {"lvl":"WRN","ts":"2023-12-06 16:05:47.727+11:00","msg":"`--nat` is set to loopback, your node wont properly announce over the DHT","topics":"codex","tid":9842787}
> {"lvl":"INF","ts":"2023-12-06 16:05:47.727+11:00","msg":"Found a network private key","tid":9842787}
> {"lvl":"INF","ts":"2023-12-06 16:05:47.731+11:00","msg":"Discovery SPR initialized","topics":"discv5","tid":9842787,"seqNum":1701839147,"uri":"spr:CiUIAhIhAlEVk3MM1HDQTFcwBFzrF4SsV9wx8VMuHVIoPUP0xP_BEgIDARo7CicAJQgCEiECURWTcwzUcNBMVzAEXOsXhKxX3DHxUy4dUig9Q_TE_8EQq4LAqwYaCgoIBAAAAAAGAAAqRjBEAiBYpgqmc6r0mlSp2GpXEv7esqmeC6mhPYLi7yE3PaO43AIgadScQbauNlx8fCc4kuWBm5erCThToyrb3nLHORiTplI"}
> {"lvl":"NOT","ts":"2023-12-06 16:05:47.733+11:00","msg":"Current bytes used for cache quota","topics":"codex repostore","tid":9842787,"bytes":0}
> {"lvl":"NOT","ts":"2023-12-06 16:05:47.733+11:00","msg":"Current bytes used for persist quota","topics":"codex repostore","tid":9842787,"bytes":0}
> {"lvl":"INF","ts":"2023-12-06 16:05:47.734+11:00","msg":"Updated discovery SPR","topics":"discv5","tid":9842787,"uri":"spr:CiUIAhIhAlEVk3MM1HDQTFcwBFzrF4SsV9wx8VMuHVIoPUP0xP_BEgIDARo7CicAJQgCEiECURWTcwzUcNBMVzAEXOsXhKxX3DHxUy4dUig9Q_TE_8EQq4LAqwYaCgoIBH8AAAEG5-kqRzBFAiEA_K0H8jRwDdbVktUI9mSqdVEOz64JsY6dzvQpNgnISy8CIBXmSde6kvfscsoZxaGrHXEpY_wGiVkjmv7ssqOw2v6y"}
> {"lvl":"INF","ts":"2023-12-06 16:05:47.734+11:00","msg":"Updated discovery SPR","topics":"discv5","tid":9842787,"uri":"spr:CiUIAhIhAlEVk3MM1HDQTFcwBFzrF4SsV9wx8VMuHVIoPUP0xP_BEgIDARo8CicAJQgCEiECURWTcwzUcNBMVzAEXOsXhKxX3DHxUy4dUig9Q_TE_8EQq4LAqwYaCwoJBH8AAAGRAh-aKkcwRQIhAIg3YCFN-IitLWNc-cfxq7TZq-ac89d0gENsrSWX8yc5AiAQDECsdG6OHqRPBdY0VDI4Yv5_GCQV7XyciDd2MccnPg"}
> {"lvl":"INF","ts":"2023-12-06 16:05:47.734+11:00","msg":"Starting discovery node","topics":"discv5","tid":9842787,"node":"2e*0ae0a3:0.0.0.0:8090"}
> {"lvl":"INF","ts":"2023-12-06 16:05:47.734+11:00","msg":"Starting transport","topics":"discv5","tid":9842787,"bindAddress":"0.0.0.0:8090"}
> {"lvl":"NOT","ts":"2023-12-06 16:05:47.734+11:00","msg":"Started codex node","topics":"codex node","tid":9842787,"id":"16Uiu2HAkztC5ucHscZwBwXwHfPm4gruJpSYqwLhNPs4MrHxDFNqW","addrs":[{"data":{"buffer":[4,0,0,0,0,6,231,233],"offset":0}}]}
> {"lvl":"NOT","ts":"2023-12-06 16:05:47.735+11:00","msg":"REST service started","tid":9842787,"address":"127.0.0.1:8080"}
> ```

I believe if it can't serialize to json it would just output it as a string, but not sure.

**Comment by emizzle** [comment]
I'll run the integration tests in debug mode to see what if it falls over at some point, just in case.

**Comment by emizzle** [comment]
> I'll run the integration tests in debug mode to see what if it falls over at some point, just in case.

Seems to work fine 👍

**Comment by emizzle** [comment]
OK to merge @dryajov?

**Review by dryajov — APPROVED** [review]
LGTM

**Comment by emizzle** [comment]
I'm gonna run extended integration tests in [another branch](https://github.com/codex-storage/nim-codex/pull/607) with `--log-format=json` first. If there's no issues, i'll merge it.

**Comment by emizzle** [comment]
`UInt256` and byte arrays are not serialized very nicely in the json sink, but this happens on master anyway. IOW, this PR doesn't affect the outcome, eg:
```shell
 {"lvl":"INF","ts":"2023-12-07 08:54:30.300+11:00","msg":"Request submitted, waiting for slots to be filled","topics":"marketplace purchases submitted","tid":10087290,"requestId":[47,160,165,53,59,186,169,8,212,34,23,145,142,4,51,120,247,6,96,136,36,177,147,171,245,223,230,217,169,30,111,210]}
{"lvl":"INF","ts":"2023-12-07 08:54:30.318+11:00","msg":"availability found for request, creating reservation","topics":"marketplace sales preparing","tid":10087496,"duration":{"data":{"lo":{"lo":100,"hi":0},"hi":{"lo":0,"hi":0}}},"pricePerSlot":{"data":{"lo":{"lo":40000,"hi":0},"hi":{"lo":0,"hi":0}}},"slotSize":{"data":{"lo":{"lo":130944,"hi":0},"hi":{"lo":0,"hi":0}}},"slotIndex":{"data":{"lo":{"lo":1,"hi":0},"hi":{"lo":0,"hi":0}}}}
```

**Comment by emizzle** [comment]
> i can create a separate PR with a logging proxy. The logging proxy can handle exceptions in chronicles exports and we can take advantage of utilities like `chronicles.formatIt(StUint) = $it` in the proxy.

@dryajov this was addressed in https://github.com/codex-storage/nim-codex/pull/653.

**Pull request merged**
